// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service_partnerdismiss.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf.WebUI {

  /// <summary>Holder for reflection information generated from service_partnerdismiss.proto</summary>
  public static partial class ServicePartnerdismissReflection {

    #region Descriptor
    /// <summary>File descriptor for service_partnerdismiss.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicePartnerdismissReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxzZXJ2aWNlX3BhcnRuZXJkaXNtaXNzLnByb3RvGiBnb29nbGUvcHJvdG9i",
            "dWYvZGVzY3JpcHRvci5wcm90bxoRY29tbW9uX2Jhc2UucHJvdG8ipAEKD0NE",
            "aXNtaXNzUGluRGF0YRIXCgVzdGF0ZRgBIAEoBUIIgrUYBGVudW0SEQoJYWNj",
            "b3VudGlkGAIgASgNEhAKCGtleV9qc29uGAMgASgJEhEKCXBhcnRuZXJpZBgE",
            "IAEoDRIUCgxydGltZV9jcmVhdGUYBSABKA0SFgoOcnRpbWVfdmFsaWRpdHkY",
            "BiABKA0SEgoKZGlzbWlzc19pZBgHIAEoBiJPCiVDUGFydG5lckRpc21pc3Nf",
            "Q3JlYXRlRGlzbWlzc19SZXF1ZXN0EiYKDGRpc21pc3NfbGlzdBgBIAMoCzIQ",
            "LkNEaXNtaXNzUGluRGF0YSJQCiZDUGFydG5lckRpc21pc3NfQ3JlYXRlRGlz",
            "bWlzc19SZXNwb25zZRImCgxkaXNtaXNzX2xpc3QYASADKAsyEC5DRGlzbWlz",
            "c1BpbkRhdGEiOwolQ1BhcnRuZXJEaXNtaXNzX0RlbGV0ZURpc21pc3NfUmVx",
            "dWVzdBISCgpkaXNtaXNzX2lkGAcgASgGIigKJkNQYXJ0bmVyRGlzbWlzc19E",
            "ZWxldGVEaXNtaXNzX1Jlc3BvbnNlImgKK0NQYXJ0bmVyRGlzbWlzc19HZXRE",
            "aXNtaXNzVGltZVJhbmdlX1JlcXVlc3QSEQoJcGFydG5lcmlkGAEgASgNEhEK",
            "CWFjY291bnRpZBgCIAEoDRITCgtydGltZV9hZnRlchgDIAEoDSJWCixDUGFy",
            "dG5lckRpc21pc3NfR2V0RGlzbWlzc1RpbWVSYW5nZV9SZXNwb25zZRImCgxk",
            "aXNtaXNzX2xpc3QYASADKAsyEC5DRGlzbWlzc1BpbkRhdGEyyAIKDlBhcnRu",
            "ZXJEaXNtaXNzEmAKDUNyZWF0ZURpc21pc3MSJi5DUGFydG5lckRpc21pc3Nf",
            "Q3JlYXRlRGlzbWlzc19SZXF1ZXN0GicuQ1BhcnRuZXJEaXNtaXNzX0NyZWF0",
            "ZURpc21pc3NfUmVzcG9uc2USYAoNRGVsZXRlRGlzbWlzcxImLkNQYXJ0bmVy",
            "RGlzbWlzc19EZWxldGVEaXNtaXNzX1JlcXVlc3QaJy5DUGFydG5lckRpc21p",
            "c3NfRGVsZXRlRGlzbWlzc19SZXNwb25zZRJyChNHZXREaXNtaXNzVGltZVJh",
            "bmdlEiwuQ1BhcnRuZXJEaXNtaXNzX0dldERpc21pc3NUaW1lUmFuZ2VfUmVx",
            "dWVzdBotLkNQYXJ0bmVyRGlzbWlzc19HZXREaXNtaXNzVGltZVJhbmdlX1Jl",
            "c3BvbnNlQiCqAh1PcGVuU3RlYW13b3Jrcy5Qcm90b2J1Zi5XZWJVSQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::OpenSteamworks.Protobuf.WebUI.CommonBaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CDismissPinData), global::OpenSteamworks.Protobuf.WebUI.CDismissPinData.Parser, new[]{ "State", "Accountid", "KeyJson", "Partnerid", "RtimeCreate", "RtimeValidity", "DismissId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_CreateDismiss_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_CreateDismiss_Request.Parser, new[]{ "DismissList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_CreateDismiss_Response), global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_CreateDismiss_Response.Parser, new[]{ "DismissList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_DeleteDismiss_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_DeleteDismiss_Request.Parser, new[]{ "DismissId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_DeleteDismiss_Response), global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_DeleteDismiss_Response.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_GetDismissTimeRange_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_GetDismissTimeRange_Request.Parser, new[]{ "Partnerid", "Accountid", "RtimeAfter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_GetDismissTimeRange_Response), global::OpenSteamworks.Protobuf.WebUI.CPartnerDismiss_GetDismissTimeRange_Response.Parser, new[]{ "DismissList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CDismissPinData : pb::IMessage<CDismissPinData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CDismissPinData> _parser = new pb::MessageParser<CDismissPinData>(() => new CDismissPinData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CDismissPinData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CDismissPinData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CDismissPinData(CDismissPinData other) : this() {
      _hasBits0 = other._hasBits0;
      state_ = other.state_;
      accountid_ = other.accountid_;
      keyJson_ = other.keyJson_;
      partnerid_ = other.partnerid_;
      rtimeCreate_ = other.rtimeCreate_;
      rtimeValidity_ = other.rtimeValidity_;
      dismissId_ = other.dismissId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CDismissPinData Clone() {
      return new CDismissPinData(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private readonly static int StateDefaultValue = 0;

    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int State {
      get { if ((_hasBits0 & 1) != 0) { return state_; } else { return StateDefaultValue; } }
      set {
        _hasBits0 |= 1;
        state_ = value;
      }
    }
    /// <summary>Gets whether the "state" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasState {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "state" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearState() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "accountid" field.</summary>
    public const int AccountidFieldNumber = 2;
    private readonly static uint AccountidDefaultValue = 0;

    private uint accountid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Accountid {
      get { if ((_hasBits0 & 2) != 0) { return accountid_; } else { return AccountidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        accountid_ = value;
      }
    }
    /// <summary>Gets whether the "accountid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "accountid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountid() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "key_json" field.</summary>
    public const int KeyJsonFieldNumber = 3;
    private readonly static string KeyJsonDefaultValue = "";

    private string keyJson_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KeyJson {
      get { return keyJson_ ?? KeyJsonDefaultValue; }
      set {
        keyJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "key_json" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKeyJson {
      get { return keyJson_ != null; }
    }
    /// <summary>Clears the value of the "key_json" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKeyJson() {
      keyJson_ = null;
    }

    /// <summary>Field number for the "partnerid" field.</summary>
    public const int PartneridFieldNumber = 4;
    private readonly static uint PartneridDefaultValue = 0;

    private uint partnerid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Partnerid {
      get { if ((_hasBits0 & 4) != 0) { return partnerid_; } else { return PartneridDefaultValue; } }
      set {
        _hasBits0 |= 4;
        partnerid_ = value;
      }
    }
    /// <summary>Gets whether the "partnerid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPartnerid {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "partnerid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPartnerid() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "rtime_create" field.</summary>
    public const int RtimeCreateFieldNumber = 5;
    private readonly static uint RtimeCreateDefaultValue = 0;

    private uint rtimeCreate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RtimeCreate {
      get { if ((_hasBits0 & 8) != 0) { return rtimeCreate_; } else { return RtimeCreateDefaultValue; } }
      set {
        _hasBits0 |= 8;
        rtimeCreate_ = value;
      }
    }
    /// <summary>Gets whether the "rtime_create" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRtimeCreate {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "rtime_create" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRtimeCreate() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "rtime_validity" field.</summary>
    public const int RtimeValidityFieldNumber = 6;
    private readonly static uint RtimeValidityDefaultValue = 0;

    private uint rtimeValidity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RtimeValidity {
      get { if ((_hasBits0 & 16) != 0) { return rtimeValidity_; } else { return RtimeValidityDefaultValue; } }
      set {
        _hasBits0 |= 16;
        rtimeValidity_ = value;
      }
    }
    /// <summary>Gets whether the "rtime_validity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRtimeValidity {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "rtime_validity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRtimeValidity() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "dismiss_id" field.</summary>
    public const int DismissIdFieldNumber = 7;
    private readonly static ulong DismissIdDefaultValue = 0UL;

    private ulong dismissId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong DismissId {
      get { if ((_hasBits0 & 32) != 0) { return dismissId_; } else { return DismissIdDefaultValue; } }
      set {
        _hasBits0 |= 32;
        dismissId_ = value;
      }
    }
    /// <summary>Gets whether the "dismiss_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDismissId {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "dismiss_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDismissId() {
      _hasBits0 &= ~32;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CDismissPinData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CDismissPinData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (State != other.State) return false;
      if (Accountid != other.Accountid) return false;
      if (KeyJson != other.KeyJson) return false;
      if (Partnerid != other.Partnerid) return false;
      if (RtimeCreate != other.RtimeCreate) return false;
      if (RtimeValidity != other.RtimeValidity) return false;
      if (DismissId != other.DismissId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasState) hash ^= State.GetHashCode();
      if (HasAccountid) hash ^= Accountid.GetHashCode();
      if (HasKeyJson) hash ^= KeyJson.GetHashCode();
      if (HasPartnerid) hash ^= Partnerid.GetHashCode();
      if (HasRtimeCreate) hash ^= RtimeCreate.GetHashCode();
      if (HasRtimeValidity) hash ^= RtimeValidity.GetHashCode();
      if (HasDismissId) hash ^= DismissId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasState) {
        output.WriteRawTag(8);
        output.WriteInt32(State);
      }
      if (HasAccountid) {
        output.WriteRawTag(16);
        output.WriteUInt32(Accountid);
      }
      if (HasKeyJson) {
        output.WriteRawTag(26);
        output.WriteString(KeyJson);
      }
      if (HasPartnerid) {
        output.WriteRawTag(32);
        output.WriteUInt32(Partnerid);
      }
      if (HasRtimeCreate) {
        output.WriteRawTag(40);
        output.WriteUInt32(RtimeCreate);
      }
      if (HasRtimeValidity) {
        output.WriteRawTag(48);
        output.WriteUInt32(RtimeValidity);
      }
      if (HasDismissId) {
        output.WriteRawTag(57);
        output.WriteFixed64(DismissId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasState) {
        output.WriteRawTag(8);
        output.WriteInt32(State);
      }
      if (HasAccountid) {
        output.WriteRawTag(16);
        output.WriteUInt32(Accountid);
      }
      if (HasKeyJson) {
        output.WriteRawTag(26);
        output.WriteString(KeyJson);
      }
      if (HasPartnerid) {
        output.WriteRawTag(32);
        output.WriteUInt32(Partnerid);
      }
      if (HasRtimeCreate) {
        output.WriteRawTag(40);
        output.WriteUInt32(RtimeCreate);
      }
      if (HasRtimeValidity) {
        output.WriteRawTag(48);
        output.WriteUInt32(RtimeValidity);
      }
      if (HasDismissId) {
        output.WriteRawTag(57);
        output.WriteFixed64(DismissId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasState) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (HasAccountid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Accountid);
      }
      if (HasKeyJson) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyJson);
      }
      if (HasPartnerid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Partnerid);
      }
      if (HasRtimeCreate) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RtimeCreate);
      }
      if (HasRtimeValidity) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RtimeValidity);
      }
      if (HasDismissId) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CDismissPinData other) {
      if (other == null) {
        return;
      }
      if (other.HasState) {
        State = other.State;
      }
      if (other.HasAccountid) {
        Accountid = other.Accountid;
      }
      if (other.HasKeyJson) {
        KeyJson = other.KeyJson;
      }
      if (other.HasPartnerid) {
        Partnerid = other.Partnerid;
      }
      if (other.HasRtimeCreate) {
        RtimeCreate = other.RtimeCreate;
      }
      if (other.HasRtimeValidity) {
        RtimeValidity = other.RtimeValidity;
      }
      if (other.HasDismissId) {
        DismissId = other.DismissId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            State = input.ReadInt32();
            break;
          }
          case 16: {
            Accountid = input.ReadUInt32();
            break;
          }
          case 26: {
            KeyJson = input.ReadString();
            break;
          }
          case 32: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 40: {
            RtimeCreate = input.ReadUInt32();
            break;
          }
          case 48: {
            RtimeValidity = input.ReadUInt32();
            break;
          }
          case 57: {
            DismissId = input.ReadFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            State = input.ReadInt32();
            break;
          }
          case 16: {
            Accountid = input.ReadUInt32();
            break;
          }
          case 26: {
            KeyJson = input.ReadString();
            break;
          }
          case 32: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 40: {
            RtimeCreate = input.ReadUInt32();
            break;
          }
          case 48: {
            RtimeValidity = input.ReadUInt32();
            break;
          }
          case 57: {
            DismissId = input.ReadFixed64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDismiss_CreateDismiss_Request : pb::IMessage<CPartnerDismiss_CreateDismiss_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDismiss_CreateDismiss_Request> _parser = new pb::MessageParser<CPartnerDismiss_CreateDismiss_Request>(() => new CPartnerDismiss_CreateDismiss_Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDismiss_CreateDismiss_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_CreateDismiss_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_CreateDismiss_Request(CPartnerDismiss_CreateDismiss_Request other) : this() {
      dismissList_ = other.dismissList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_CreateDismiss_Request Clone() {
      return new CPartnerDismiss_CreateDismiss_Request(this);
    }

    /// <summary>Field number for the "dismiss_list" field.</summary>
    public const int DismissListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> _repeated_dismissList_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.CDismissPinData.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> dismissList_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> DismissList {
      get { return dismissList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDismiss_CreateDismiss_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDismiss_CreateDismiss_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dismissList_.Equals(other.dismissList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dismissList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dismissList_.WriteTo(output, _repeated_dismissList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dismissList_.WriteTo(ref output, _repeated_dismissList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += dismissList_.CalculateSize(_repeated_dismissList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDismiss_CreateDismiss_Request other) {
      if (other == null) {
        return;
      }
      dismissList_.Add(other.dismissList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dismissList_.AddEntriesFrom(input, _repeated_dismissList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dismissList_.AddEntriesFrom(ref input, _repeated_dismissList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDismiss_CreateDismiss_Response : pb::IMessage<CPartnerDismiss_CreateDismiss_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDismiss_CreateDismiss_Response> _parser = new pb::MessageParser<CPartnerDismiss_CreateDismiss_Response>(() => new CPartnerDismiss_CreateDismiss_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDismiss_CreateDismiss_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_CreateDismiss_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_CreateDismiss_Response(CPartnerDismiss_CreateDismiss_Response other) : this() {
      dismissList_ = other.dismissList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_CreateDismiss_Response Clone() {
      return new CPartnerDismiss_CreateDismiss_Response(this);
    }

    /// <summary>Field number for the "dismiss_list" field.</summary>
    public const int DismissListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> _repeated_dismissList_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.CDismissPinData.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> dismissList_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> DismissList {
      get { return dismissList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDismiss_CreateDismiss_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDismiss_CreateDismiss_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dismissList_.Equals(other.dismissList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dismissList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dismissList_.WriteTo(output, _repeated_dismissList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dismissList_.WriteTo(ref output, _repeated_dismissList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += dismissList_.CalculateSize(_repeated_dismissList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDismiss_CreateDismiss_Response other) {
      if (other == null) {
        return;
      }
      dismissList_.Add(other.dismissList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dismissList_.AddEntriesFrom(input, _repeated_dismissList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dismissList_.AddEntriesFrom(ref input, _repeated_dismissList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDismiss_DeleteDismiss_Request : pb::IMessage<CPartnerDismiss_DeleteDismiss_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDismiss_DeleteDismiss_Request> _parser = new pb::MessageParser<CPartnerDismiss_DeleteDismiss_Request>(() => new CPartnerDismiss_DeleteDismiss_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDismiss_DeleteDismiss_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_DeleteDismiss_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_DeleteDismiss_Request(CPartnerDismiss_DeleteDismiss_Request other) : this() {
      _hasBits0 = other._hasBits0;
      dismissId_ = other.dismissId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_DeleteDismiss_Request Clone() {
      return new CPartnerDismiss_DeleteDismiss_Request(this);
    }

    /// <summary>Field number for the "dismiss_id" field.</summary>
    public const int DismissIdFieldNumber = 7;
    private readonly static ulong DismissIdDefaultValue = 0UL;

    private ulong dismissId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong DismissId {
      get { if ((_hasBits0 & 1) != 0) { return dismissId_; } else { return DismissIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        dismissId_ = value;
      }
    }
    /// <summary>Gets whether the "dismiss_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDismissId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "dismiss_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDismissId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDismiss_DeleteDismiss_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDismiss_DeleteDismiss_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DismissId != other.DismissId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDismissId) hash ^= DismissId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDismissId) {
        output.WriteRawTag(57);
        output.WriteFixed64(DismissId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDismissId) {
        output.WriteRawTag(57);
        output.WriteFixed64(DismissId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasDismissId) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDismiss_DeleteDismiss_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasDismissId) {
        DismissId = other.DismissId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 57: {
            DismissId = input.ReadFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 57: {
            DismissId = input.ReadFixed64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDismiss_DeleteDismiss_Response : pb::IMessage<CPartnerDismiss_DeleteDismiss_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDismiss_DeleteDismiss_Response> _parser = new pb::MessageParser<CPartnerDismiss_DeleteDismiss_Response>(() => new CPartnerDismiss_DeleteDismiss_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDismiss_DeleteDismiss_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_DeleteDismiss_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_DeleteDismiss_Response(CPartnerDismiss_DeleteDismiss_Response other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_DeleteDismiss_Response Clone() {
      return new CPartnerDismiss_DeleteDismiss_Response(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDismiss_DeleteDismiss_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDismiss_DeleteDismiss_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDismiss_DeleteDismiss_Response other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDismiss_GetDismissTimeRange_Request : pb::IMessage<CPartnerDismiss_GetDismissTimeRange_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDismiss_GetDismissTimeRange_Request> _parser = new pb::MessageParser<CPartnerDismiss_GetDismissTimeRange_Request>(() => new CPartnerDismiss_GetDismissTimeRange_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDismiss_GetDismissTimeRange_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_GetDismissTimeRange_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_GetDismissTimeRange_Request(CPartnerDismiss_GetDismissTimeRange_Request other) : this() {
      _hasBits0 = other._hasBits0;
      partnerid_ = other.partnerid_;
      accountid_ = other.accountid_;
      rtimeAfter_ = other.rtimeAfter_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_GetDismissTimeRange_Request Clone() {
      return new CPartnerDismiss_GetDismissTimeRange_Request(this);
    }

    /// <summary>Field number for the "partnerid" field.</summary>
    public const int PartneridFieldNumber = 1;
    private readonly static uint PartneridDefaultValue = 0;

    private uint partnerid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Partnerid {
      get { if ((_hasBits0 & 1) != 0) { return partnerid_; } else { return PartneridDefaultValue; } }
      set {
        _hasBits0 |= 1;
        partnerid_ = value;
      }
    }
    /// <summary>Gets whether the "partnerid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPartnerid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "partnerid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPartnerid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "accountid" field.</summary>
    public const int AccountidFieldNumber = 2;
    private readonly static uint AccountidDefaultValue = 0;

    private uint accountid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Accountid {
      get { if ((_hasBits0 & 2) != 0) { return accountid_; } else { return AccountidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        accountid_ = value;
      }
    }
    /// <summary>Gets whether the "accountid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "accountid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountid() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "rtime_after" field.</summary>
    public const int RtimeAfterFieldNumber = 3;
    private readonly static uint RtimeAfterDefaultValue = 0;

    private uint rtimeAfter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RtimeAfter {
      get { if ((_hasBits0 & 4) != 0) { return rtimeAfter_; } else { return RtimeAfterDefaultValue; } }
      set {
        _hasBits0 |= 4;
        rtimeAfter_ = value;
      }
    }
    /// <summary>Gets whether the "rtime_after" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRtimeAfter {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "rtime_after" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRtimeAfter() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDismiss_GetDismissTimeRange_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDismiss_GetDismissTimeRange_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Partnerid != other.Partnerid) return false;
      if (Accountid != other.Accountid) return false;
      if (RtimeAfter != other.RtimeAfter) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPartnerid) hash ^= Partnerid.GetHashCode();
      if (HasAccountid) hash ^= Accountid.GetHashCode();
      if (HasRtimeAfter) hash ^= RtimeAfter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      if (HasAccountid) {
        output.WriteRawTag(16);
        output.WriteUInt32(Accountid);
      }
      if (HasRtimeAfter) {
        output.WriteRawTag(24);
        output.WriteUInt32(RtimeAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      if (HasAccountid) {
        output.WriteRawTag(16);
        output.WriteUInt32(Accountid);
      }
      if (HasRtimeAfter) {
        output.WriteRawTag(24);
        output.WriteUInt32(RtimeAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPartnerid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Partnerid);
      }
      if (HasAccountid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Accountid);
      }
      if (HasRtimeAfter) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RtimeAfter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDismiss_GetDismissTimeRange_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasPartnerid) {
        Partnerid = other.Partnerid;
      }
      if (other.HasAccountid) {
        Accountid = other.Accountid;
      }
      if (other.HasRtimeAfter) {
        RtimeAfter = other.RtimeAfter;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 16: {
            Accountid = input.ReadUInt32();
            break;
          }
          case 24: {
            RtimeAfter = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 16: {
            Accountid = input.ReadUInt32();
            break;
          }
          case 24: {
            RtimeAfter = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDismiss_GetDismissTimeRange_Response : pb::IMessage<CPartnerDismiss_GetDismissTimeRange_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDismiss_GetDismissTimeRange_Response> _parser = new pb::MessageParser<CPartnerDismiss_GetDismissTimeRange_Response>(() => new CPartnerDismiss_GetDismissTimeRange_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDismiss_GetDismissTimeRange_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdismissReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_GetDismissTimeRange_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_GetDismissTimeRange_Response(CPartnerDismiss_GetDismissTimeRange_Response other) : this() {
      dismissList_ = other.dismissList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDismiss_GetDismissTimeRange_Response Clone() {
      return new CPartnerDismiss_GetDismissTimeRange_Response(this);
    }

    /// <summary>Field number for the "dismiss_list" field.</summary>
    public const int DismissListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> _repeated_dismissList_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.CDismissPinData.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> dismissList_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CDismissPinData> DismissList {
      get { return dismissList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDismiss_GetDismissTimeRange_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDismiss_GetDismissTimeRange_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dismissList_.Equals(other.dismissList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dismissList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dismissList_.WriteTo(output, _repeated_dismissList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dismissList_.WriteTo(ref output, _repeated_dismissList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += dismissList_.CalculateSize(_repeated_dismissList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDismiss_GetDismissTimeRange_Response other) {
      if (other == null) {
        return;
      }
      dismissList_.Add(other.dismissList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dismissList_.AddEntriesFrom(input, _repeated_dismissList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dismissList_.AddEntriesFrom(ref input, _repeated_dismissList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
