// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service_promotionstats.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf.WebUI {

  /// <summary>Holder for reflection information generated from service_promotionstats.proto</summary>
  public static partial class ServicePromotionstatsReflection {

    #region Descriptor
    /// <summary>File descriptor for service_promotionstats.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicePromotionstatsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxzZXJ2aWNlX3Byb21vdGlvbnN0YXRzLnByb3RvGiBnb29nbGUvcHJvdG9i",
            "dWYvZGVzY3JpcHRvci5wcm90byJACilDUHJvbW90aW9uU3RhdHNfR2V0T3B0",
            "SW5EZW1vU3RhdHNfUmVxdWVzdBITCgtvcHRfaW5fbmFtZRgBIAEoCSJ0CipD",
            "UHJvbW90aW9uU3RhdHNfR2V0T3B0SW5EZW1vU3RhdHNfUmVzcG9uc2USRgoF",
            "c3RhdHMYASADKAsyNy5DUHJvbW90aW9uU3RhdHNfR2V0T3B0SW5EZW1vU3Rh",
            "dHNfUmVzcG9uc2VfUGVyQXBwU3RhdHMi2QEKNkNQcm9tb3Rpb25TdGF0c19H",
            "ZXRPcHRJbkRlbW9TdGF0c19SZXNwb25zZV9QZXJBcHBTdGF0cxINCgVhcHBp",
            "ZBgBIAEoDRISCgpkZW1vX2FwcGlkGAIgASgNEhUKDXJ0X3N0YXJ0X3RpbWUY",
            "AyABKA0SEwoLcnRfZW5kX3RpbWUYBCABKA0SGQoRZGVtb19wbGF5ZXJfY291",
            "bnQYBSABKA0SFgoOd2lzaGxpc3RfY291bnQYBiABKA0SHQoVcGxheWVyX3dp",
            "c2hsaXN0X2NvdW50GAcgASgNMn4KDlByb21vdGlvblN0YXRzEmwKEUdldE9w",
            "dEluRGVtb1N0YXRzEiouQ1Byb21vdGlvblN0YXRzX0dldE9wdEluRGVtb1N0",
            "YXRzX1JlcXVlc3QaKy5DUHJvbW90aW9uU3RhdHNfR2V0T3B0SW5EZW1vU3Rh",
            "dHNfUmVzcG9uc2VCIKoCHU9wZW5TdGVhbXdvcmtzLlByb3RvYnVmLldlYlVJ"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Request), global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Request.Parser, new[]{ "OptInName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response), global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response.Parser, new[]{ "Stats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats), global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats.Parser, new[]{ "Appid", "DemoAppid", "RtStartTime", "RtEndTime", "DemoPlayerCount", "WishlistCount", "PlayerWishlistCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPromotionStats_GetOptInDemoStats_Request : pb::IMessage<CPromotionStats_GetOptInDemoStats_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPromotionStats_GetOptInDemoStats_Request> _parser = new pb::MessageParser<CPromotionStats_GetOptInDemoStats_Request>(() => new CPromotionStats_GetOptInDemoStats_Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPromotionStats_GetOptInDemoStats_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePromotionstatsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Request(CPromotionStats_GetOptInDemoStats_Request other) : this() {
      optInName_ = other.optInName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Request Clone() {
      return new CPromotionStats_GetOptInDemoStats_Request(this);
    }

    /// <summary>Field number for the "opt_in_name" field.</summary>
    public const int OptInNameFieldNumber = 1;
    private readonly static string OptInNameDefaultValue = "";

    private string optInName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OptInName {
      get { return optInName_ ?? OptInNameDefaultValue; }
      set {
        optInName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "opt_in_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOptInName {
      get { return optInName_ != null; }
    }
    /// <summary>Clears the value of the "opt_in_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptInName() {
      optInName_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPromotionStats_GetOptInDemoStats_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPromotionStats_GetOptInDemoStats_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OptInName != other.OptInName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOptInName) hash ^= OptInName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOptInName) {
        output.WriteRawTag(10);
        output.WriteString(OptInName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOptInName) {
        output.WriteRawTag(10);
        output.WriteString(OptInName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOptInName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OptInName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPromotionStats_GetOptInDemoStats_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasOptInName) {
        OptInName = other.OptInName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OptInName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OptInName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPromotionStats_GetOptInDemoStats_Response : pb::IMessage<CPromotionStats_GetOptInDemoStats_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPromotionStats_GetOptInDemoStats_Response> _parser = new pb::MessageParser<CPromotionStats_GetOptInDemoStats_Response>(() => new CPromotionStats_GetOptInDemoStats_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPromotionStats_GetOptInDemoStats_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePromotionstatsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Response(CPromotionStats_GetOptInDemoStats_Response other) : this() {
      stats_ = other.stats_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Response Clone() {
      return new CPromotionStats_GetOptInDemoStats_Response(this);
    }

    /// <summary>Field number for the "stats" field.</summary>
    public const int StatsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats> _repeated_stats_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats> stats_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPromotionStats_GetOptInDemoStats_Response_PerAppStats> Stats {
      get { return stats_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPromotionStats_GetOptInDemoStats_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPromotionStats_GetOptInDemoStats_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stats_.Equals(other.stats_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stats_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      stats_.WriteTo(output, _repeated_stats_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      stats_.WriteTo(ref output, _repeated_stats_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += stats_.CalculateSize(_repeated_stats_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPromotionStats_GetOptInDemoStats_Response other) {
      if (other == null) {
        return;
      }
      stats_.Add(other.stats_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            stats_.AddEntriesFrom(input, _repeated_stats_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            stats_.AddEntriesFrom(ref input, _repeated_stats_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPromotionStats_GetOptInDemoStats_Response_PerAppStats : pb::IMessage<CPromotionStats_GetOptInDemoStats_Response_PerAppStats>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPromotionStats_GetOptInDemoStats_Response_PerAppStats> _parser = new pb::MessageParser<CPromotionStats_GetOptInDemoStats_Response_PerAppStats>(() => new CPromotionStats_GetOptInDemoStats_Response_PerAppStats());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPromotionStats_GetOptInDemoStats_Response_PerAppStats> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePromotionstatsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Response_PerAppStats() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Response_PerAppStats(CPromotionStats_GetOptInDemoStats_Response_PerAppStats other) : this() {
      _hasBits0 = other._hasBits0;
      appid_ = other.appid_;
      demoAppid_ = other.demoAppid_;
      rtStartTime_ = other.rtStartTime_;
      rtEndTime_ = other.rtEndTime_;
      demoPlayerCount_ = other.demoPlayerCount_;
      wishlistCount_ = other.wishlistCount_;
      playerWishlistCount_ = other.playerWishlistCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPromotionStats_GetOptInDemoStats_Response_PerAppStats Clone() {
      return new CPromotionStats_GetOptInDemoStats_Response_PerAppStats(this);
    }

    /// <summary>Field number for the "appid" field.</summary>
    public const int AppidFieldNumber = 1;
    private readonly static uint AppidDefaultValue = 0;

    private uint appid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Appid {
      get { if ((_hasBits0 & 1) != 0) { return appid_; } else { return AppidDefaultValue; } }
      set {
        _hasBits0 |= 1;
        appid_ = value;
      }
    }
    /// <summary>Gets whether the "appid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "appid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "demo_appid" field.</summary>
    public const int DemoAppidFieldNumber = 2;
    private readonly static uint DemoAppidDefaultValue = 0;

    private uint demoAppid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DemoAppid {
      get { if ((_hasBits0 & 2) != 0) { return demoAppid_; } else { return DemoAppidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        demoAppid_ = value;
      }
    }
    /// <summary>Gets whether the "demo_appid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDemoAppid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "demo_appid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDemoAppid() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "rt_start_time" field.</summary>
    public const int RtStartTimeFieldNumber = 3;
    private readonly static uint RtStartTimeDefaultValue = 0;

    private uint rtStartTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RtStartTime {
      get { if ((_hasBits0 & 4) != 0) { return rtStartTime_; } else { return RtStartTimeDefaultValue; } }
      set {
        _hasBits0 |= 4;
        rtStartTime_ = value;
      }
    }
    /// <summary>Gets whether the "rt_start_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRtStartTime {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "rt_start_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRtStartTime() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "rt_end_time" field.</summary>
    public const int RtEndTimeFieldNumber = 4;
    private readonly static uint RtEndTimeDefaultValue = 0;

    private uint rtEndTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RtEndTime {
      get { if ((_hasBits0 & 8) != 0) { return rtEndTime_; } else { return RtEndTimeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        rtEndTime_ = value;
      }
    }
    /// <summary>Gets whether the "rt_end_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRtEndTime {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "rt_end_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRtEndTime() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "demo_player_count" field.</summary>
    public const int DemoPlayerCountFieldNumber = 5;
    private readonly static uint DemoPlayerCountDefaultValue = 0;

    private uint demoPlayerCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DemoPlayerCount {
      get { if ((_hasBits0 & 16) != 0) { return demoPlayerCount_; } else { return DemoPlayerCountDefaultValue; } }
      set {
        _hasBits0 |= 16;
        demoPlayerCount_ = value;
      }
    }
    /// <summary>Gets whether the "demo_player_count" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDemoPlayerCount {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "demo_player_count" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDemoPlayerCount() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "wishlist_count" field.</summary>
    public const int WishlistCountFieldNumber = 6;
    private readonly static uint WishlistCountDefaultValue = 0;

    private uint wishlistCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint WishlistCount {
      get { if ((_hasBits0 & 32) != 0) { return wishlistCount_; } else { return WishlistCountDefaultValue; } }
      set {
        _hasBits0 |= 32;
        wishlistCount_ = value;
      }
    }
    /// <summary>Gets whether the "wishlist_count" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWishlistCount {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "wishlist_count" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWishlistCount() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "player_wishlist_count" field.</summary>
    public const int PlayerWishlistCountFieldNumber = 7;
    private readonly static uint PlayerWishlistCountDefaultValue = 0;

    private uint playerWishlistCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PlayerWishlistCount {
      get { if ((_hasBits0 & 64) != 0) { return playerWishlistCount_; } else { return PlayerWishlistCountDefaultValue; } }
      set {
        _hasBits0 |= 64;
        playerWishlistCount_ = value;
      }
    }
    /// <summary>Gets whether the "player_wishlist_count" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlayerWishlistCount {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "player_wishlist_count" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlayerWishlistCount() {
      _hasBits0 &= ~64;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPromotionStats_GetOptInDemoStats_Response_PerAppStats);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPromotionStats_GetOptInDemoStats_Response_PerAppStats other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Appid != other.Appid) return false;
      if (DemoAppid != other.DemoAppid) return false;
      if (RtStartTime != other.RtStartTime) return false;
      if (RtEndTime != other.RtEndTime) return false;
      if (DemoPlayerCount != other.DemoPlayerCount) return false;
      if (WishlistCount != other.WishlistCount) return false;
      if (PlayerWishlistCount != other.PlayerWishlistCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAppid) hash ^= Appid.GetHashCode();
      if (HasDemoAppid) hash ^= DemoAppid.GetHashCode();
      if (HasRtStartTime) hash ^= RtStartTime.GetHashCode();
      if (HasRtEndTime) hash ^= RtEndTime.GetHashCode();
      if (HasDemoPlayerCount) hash ^= DemoPlayerCount.GetHashCode();
      if (HasWishlistCount) hash ^= WishlistCount.GetHashCode();
      if (HasPlayerWishlistCount) hash ^= PlayerWishlistCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAppid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Appid);
      }
      if (HasDemoAppid) {
        output.WriteRawTag(16);
        output.WriteUInt32(DemoAppid);
      }
      if (HasRtStartTime) {
        output.WriteRawTag(24);
        output.WriteUInt32(RtStartTime);
      }
      if (HasRtEndTime) {
        output.WriteRawTag(32);
        output.WriteUInt32(RtEndTime);
      }
      if (HasDemoPlayerCount) {
        output.WriteRawTag(40);
        output.WriteUInt32(DemoPlayerCount);
      }
      if (HasWishlistCount) {
        output.WriteRawTag(48);
        output.WriteUInt32(WishlistCount);
      }
      if (HasPlayerWishlistCount) {
        output.WriteRawTag(56);
        output.WriteUInt32(PlayerWishlistCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAppid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Appid);
      }
      if (HasDemoAppid) {
        output.WriteRawTag(16);
        output.WriteUInt32(DemoAppid);
      }
      if (HasRtStartTime) {
        output.WriteRawTag(24);
        output.WriteUInt32(RtStartTime);
      }
      if (HasRtEndTime) {
        output.WriteRawTag(32);
        output.WriteUInt32(RtEndTime);
      }
      if (HasDemoPlayerCount) {
        output.WriteRawTag(40);
        output.WriteUInt32(DemoPlayerCount);
      }
      if (HasWishlistCount) {
        output.WriteRawTag(48);
        output.WriteUInt32(WishlistCount);
      }
      if (HasPlayerWishlistCount) {
        output.WriteRawTag(56);
        output.WriteUInt32(PlayerWishlistCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAppid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Appid);
      }
      if (HasDemoAppid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DemoAppid);
      }
      if (HasRtStartTime) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RtStartTime);
      }
      if (HasRtEndTime) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RtEndTime);
      }
      if (HasDemoPlayerCount) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DemoPlayerCount);
      }
      if (HasWishlistCount) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WishlistCount);
      }
      if (HasPlayerWishlistCount) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerWishlistCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPromotionStats_GetOptInDemoStats_Response_PerAppStats other) {
      if (other == null) {
        return;
      }
      if (other.HasAppid) {
        Appid = other.Appid;
      }
      if (other.HasDemoAppid) {
        DemoAppid = other.DemoAppid;
      }
      if (other.HasRtStartTime) {
        RtStartTime = other.RtStartTime;
      }
      if (other.HasRtEndTime) {
        RtEndTime = other.RtEndTime;
      }
      if (other.HasDemoPlayerCount) {
        DemoPlayerCount = other.DemoPlayerCount;
      }
      if (other.HasWishlistCount) {
        WishlistCount = other.WishlistCount;
      }
      if (other.HasPlayerWishlistCount) {
        PlayerWishlistCount = other.PlayerWishlistCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Appid = input.ReadUInt32();
            break;
          }
          case 16: {
            DemoAppid = input.ReadUInt32();
            break;
          }
          case 24: {
            RtStartTime = input.ReadUInt32();
            break;
          }
          case 32: {
            RtEndTime = input.ReadUInt32();
            break;
          }
          case 40: {
            DemoPlayerCount = input.ReadUInt32();
            break;
          }
          case 48: {
            WishlistCount = input.ReadUInt32();
            break;
          }
          case 56: {
            PlayerWishlistCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Appid = input.ReadUInt32();
            break;
          }
          case 16: {
            DemoAppid = input.ReadUInt32();
            break;
          }
          case 24: {
            RtStartTime = input.ReadUInt32();
            break;
          }
          case 32: {
            RtEndTime = input.ReadUInt32();
            break;
          }
          case 40: {
            DemoPlayerCount = input.ReadUInt32();
            break;
          }
          case 48: {
            WishlistCount = input.ReadUInt32();
            break;
          }
          case 56: {
            PlayerWishlistCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
