// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service_partnerstorebrowse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf.WebUI {

  /// <summary>Holder for reflection information generated from service_partnerstorebrowse.proto</summary>
  public static partial class ServicePartnerstorebrowseReflection {

    #region Descriptor
    /// <summary>File descriptor for service_partnerstorebrowse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicePartnerstorebrowseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBzZXJ2aWNlX3BhcnRuZXJzdG9yZWJyb3dzZS5wcm90bxogZ29vZ2xlL3By",
            "b3RvYnVmL2Rlc2NyaXB0b3IucHJvdG8aDGNvbW1vbi5wcm90byJPCjJDUGFy",
            "dG5lclN0b3JlQnJvd3NlX0dldENvdW50cnlSZXN0cmljdGlvbnNfUmVxdWVz",
            "dBIZCgNpZHMYASADKAsyDC5TdG9yZUl0ZW1JRCKwAQozQ1BhcnRuZXJTdG9y",
            "ZUJyb3dzZV9HZXRDb3VudHJ5UmVzdHJpY3Rpb25zX1Jlc3BvbnNlEloKB3Jl",
            "c3VsdHMYASADKAsySS5DUGFydG5lclN0b3JlQnJvd3NlX0dldENvdW50cnlS",
            "ZXN0cmljdGlvbnNfUmVzcG9uc2VfQ0NvdW50cnlSZXN0cmljdGlvbnMSHQoH",
            "bm9faW5mbxgCIAMoCzIMLlN0b3JlSXRlbUlEIrYBCkhDUGFydG5lclN0b3Jl",
            "QnJvd3NlX0dldENvdW50cnlSZXN0cmljdGlvbnNfUmVzcG9uc2VfQ0NvdW50",
            "cnlSZXN0cmljdGlvbnMSGAoCaWQYASABKAsyDC5TdG9yZUl0ZW1JRBIXCg9u",
            "b19yZXN0cmljdGlvbnMYAiABKAgSGQoRYWxsb3dlZF9jb3VudHJpZXMYAyAD",
            "KAkSHAoUcmVzdHJpY3RlZF9jb3VudHJpZXMYBCADKAkidAokQ1BhcnRuZXJT",
            "dG9yZUJyb3dzZV9HZXRJdGVtc19SZXF1ZXN0Ei8KB3JlcXVlc3QYASABKAsy",
            "Hi5DU3RvcmVCcm93c2VfR2V0SXRlbXNfUmVxdWVzdBIbChNpbmNsdWRlX3Vu",
            "cHVibGlzaGVkGAIgASgIMu4BChJQYXJ0bmVyU3RvcmVCcm93c2USgwEKFkdl",
            "dENvdW50cnlSZXN0cmljdGlvbnMSMy5DUGFydG5lclN0b3JlQnJvd3NlX0dl",
            "dENvdW50cnlSZXN0cmljdGlvbnNfUmVxdWVzdBo0LkNQYXJ0bmVyU3RvcmVC",
            "cm93c2VfR2V0Q291bnRyeVJlc3RyaWN0aW9uc19SZXNwb25zZRJSCghHZXRJ",
            "dGVtcxIlLkNQYXJ0bmVyU3RvcmVCcm93c2VfR2V0SXRlbXNfUmVxdWVzdBof",
            "LkNTdG9yZUJyb3dzZV9HZXRJdGVtc19SZXNwb25zZUIgqgIdT3BlblN0ZWFt",
            "d29ya3MuUHJvdG9idWYuV2ViVUk="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::OpenSteamworks.Protobuf.WebUI.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Request.Parser, new[]{ "Ids" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response), global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response.Parser, new[]{ "Results", "NoInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions), global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions.Parser, new[]{ "Id", "NoRestrictions", "AllowedCountries", "RestrictedCountries" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetItems_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetItems_Request.Parser, new[]{ "Request", "IncludeUnpublished" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerStoreBrowse_GetCountryRestrictions_Request : pb::IMessage<CPartnerStoreBrowse_GetCountryRestrictions_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Request> _parser = new pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Request>(() => new CPartnerStoreBrowse_GetCountryRestrictions_Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerstorebrowseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Request(CPartnerStoreBrowse_GetCountryRestrictions_Request other) : this() {
      ids_ = other.ids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Request Clone() {
      return new CPartnerStoreBrowse_GetCountryRestrictions_Request(this);
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.StoreItemID> _repeated_ids_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.StoreItemID.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.StoreItemID> ids_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.StoreItemID>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.StoreItemID> Ids {
      get { return ids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerStoreBrowse_GetCountryRestrictions_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerStoreBrowse_GetCountryRestrictions_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!ids_.Equals(other.ids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      ids_.WriteTo(output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      ids_.WriteTo(ref output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerStoreBrowse_GetCountryRestrictions_Request other) {
      if (other == null) {
        return;
      }
      ids_.Add(other.ids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ids_.AddEntriesFrom(ref input, _repeated_ids_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerStoreBrowse_GetCountryRestrictions_Response : pb::IMessage<CPartnerStoreBrowse_GetCountryRestrictions_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Response> _parser = new pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Response>(() => new CPartnerStoreBrowse_GetCountryRestrictions_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerstorebrowseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Response(CPartnerStoreBrowse_GetCountryRestrictions_Response other) : this() {
      results_ = other.results_.Clone();
      noInfo_ = other.noInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Response Clone() {
      return new CPartnerStoreBrowse_GetCountryRestrictions_Response(this);
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions> _repeated_results_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions> results_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions> Results {
      get { return results_; }
    }

    /// <summary>Field number for the "no_info" field.</summary>
    public const int NoInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.StoreItemID> _repeated_noInfo_codec
        = pb::FieldCodec.ForMessage(18, global::OpenSteamworks.Protobuf.WebUI.StoreItemID.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.StoreItemID> noInfo_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.StoreItemID>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.StoreItemID> NoInfo {
      get { return noInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerStoreBrowse_GetCountryRestrictions_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerStoreBrowse_GetCountryRestrictions_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!results_.Equals(other.results_)) return false;
      if(!noInfo_.Equals(other.noInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= results_.GetHashCode();
      hash ^= noInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      results_.WriteTo(output, _repeated_results_codec);
      noInfo_.WriteTo(output, _repeated_noInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      results_.WriteTo(ref output, _repeated_results_codec);
      noInfo_.WriteTo(ref output, _repeated_noInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += results_.CalculateSize(_repeated_results_codec);
      size += noInfo_.CalculateSize(_repeated_noInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerStoreBrowse_GetCountryRestrictions_Response other) {
      if (other == null) {
        return;
      }
      results_.Add(other.results_);
      noInfo_.Add(other.noInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
          case 18: {
            noInfo_.AddEntriesFrom(input, _repeated_noInfo_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            results_.AddEntriesFrom(ref input, _repeated_results_codec);
            break;
          }
          case 18: {
            noInfo_.AddEntriesFrom(ref input, _repeated_noInfo_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions : pb::IMessage<CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions> _parser = new pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions>(() => new CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerstorebrowseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions(CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_ != null ? other.id_.Clone() : null;
      noRestrictions_ = other.noRestrictions_;
      allowedCountries_ = other.allowedCountries_.Clone();
      restrictedCountries_ = other.restrictedCountries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions Clone() {
      return new CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::OpenSteamworks.Protobuf.WebUI.StoreItemID id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenSteamworks.Protobuf.WebUI.StoreItemID Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "no_restrictions" field.</summary>
    public const int NoRestrictionsFieldNumber = 2;
    private readonly static bool NoRestrictionsDefaultValue = false;

    private bool noRestrictions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NoRestrictions {
      get { if ((_hasBits0 & 1) != 0) { return noRestrictions_; } else { return NoRestrictionsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        noRestrictions_ = value;
      }
    }
    /// <summary>Gets whether the "no_restrictions" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNoRestrictions {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "no_restrictions" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNoRestrictions() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "allowed_countries" field.</summary>
    public const int AllowedCountriesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_allowedCountries_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> allowedCountries_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> AllowedCountries {
      get { return allowedCountries_; }
    }

    /// <summary>Field number for the "restricted_countries" field.</summary>
    public const int RestrictedCountriesFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_restrictedCountries_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> restrictedCountries_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RestrictedCountries {
      get { return restrictedCountries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (NoRestrictions != other.NoRestrictions) return false;
      if(!allowedCountries_.Equals(other.allowedCountries_)) return false;
      if(!restrictedCountries_.Equals(other.restrictedCountries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (HasNoRestrictions) hash ^= NoRestrictions.GetHashCode();
      hash ^= allowedCountries_.GetHashCode();
      hash ^= restrictedCountries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (HasNoRestrictions) {
        output.WriteRawTag(16);
        output.WriteBool(NoRestrictions);
      }
      allowedCountries_.WriteTo(output, _repeated_allowedCountries_codec);
      restrictedCountries_.WriteTo(output, _repeated_restrictedCountries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (HasNoRestrictions) {
        output.WriteRawTag(16);
        output.WriteBool(NoRestrictions);
      }
      allowedCountries_.WriteTo(ref output, _repeated_allowedCountries_codec);
      restrictedCountries_.WriteTo(ref output, _repeated_restrictedCountries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (HasNoRestrictions) {
        size += 1 + 1;
      }
      size += allowedCountries_.CalculateSize(_repeated_allowedCountries_codec);
      size += restrictedCountries_.CalculateSize(_repeated_restrictedCountries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerStoreBrowse_GetCountryRestrictions_Response_CCountryRestrictions other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::OpenSteamworks.Protobuf.WebUI.StoreItemID();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.HasNoRestrictions) {
        NoRestrictions = other.NoRestrictions;
      }
      allowedCountries_.Add(other.allowedCountries_);
      restrictedCountries_.Add(other.restrictedCountries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::OpenSteamworks.Protobuf.WebUI.StoreItemID();
            }
            input.ReadMessage(Id);
            break;
          }
          case 16: {
            NoRestrictions = input.ReadBool();
            break;
          }
          case 26: {
            allowedCountries_.AddEntriesFrom(input, _repeated_allowedCountries_codec);
            break;
          }
          case 34: {
            restrictedCountries_.AddEntriesFrom(input, _repeated_restrictedCountries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::OpenSteamworks.Protobuf.WebUI.StoreItemID();
            }
            input.ReadMessage(Id);
            break;
          }
          case 16: {
            NoRestrictions = input.ReadBool();
            break;
          }
          case 26: {
            allowedCountries_.AddEntriesFrom(ref input, _repeated_allowedCountries_codec);
            break;
          }
          case 34: {
            restrictedCountries_.AddEntriesFrom(ref input, _repeated_restrictedCountries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerStoreBrowse_GetItems_Request : pb::IMessage<CPartnerStoreBrowse_GetItems_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerStoreBrowse_GetItems_Request> _parser = new pb::MessageParser<CPartnerStoreBrowse_GetItems_Request>(() => new CPartnerStoreBrowse_GetItems_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerStoreBrowse_GetItems_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerstorebrowseReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetItems_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetItems_Request(CPartnerStoreBrowse_GetItems_Request other) : this() {
      _hasBits0 = other._hasBits0;
      request_ = other.request_ != null ? other.request_.Clone() : null;
      includeUnpublished_ = other.includeUnpublished_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerStoreBrowse_GetItems_Request Clone() {
      return new CPartnerStoreBrowse_GetItems_Request(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::OpenSteamworks.Protobuf.WebUI.CStoreBrowse_GetItems_Request request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenSteamworks.Protobuf.WebUI.CStoreBrowse_GetItems_Request Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "include_unpublished" field.</summary>
    public const int IncludeUnpublishedFieldNumber = 2;
    private readonly static bool IncludeUnpublishedDefaultValue = false;

    private bool includeUnpublished_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeUnpublished {
      get { if ((_hasBits0 & 1) != 0) { return includeUnpublished_; } else { return IncludeUnpublishedDefaultValue; } }
      set {
        _hasBits0 |= 1;
        includeUnpublished_ = value;
      }
    }
    /// <summary>Gets whether the "include_unpublished" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIncludeUnpublished {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "include_unpublished" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIncludeUnpublished() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerStoreBrowse_GetItems_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerStoreBrowse_GetItems_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if (IncludeUnpublished != other.IncludeUnpublished) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      if (HasIncludeUnpublished) hash ^= IncludeUnpublished.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (HasIncludeUnpublished) {
        output.WriteRawTag(16);
        output.WriteBool(IncludeUnpublished);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (HasIncludeUnpublished) {
        output.WriteRawTag(16);
        output.WriteBool(IncludeUnpublished);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (HasIncludeUnpublished) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerStoreBrowse_GetItems_Request other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::OpenSteamworks.Protobuf.WebUI.CStoreBrowse_GetItems_Request();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.HasIncludeUnpublished) {
        IncludeUnpublished = other.IncludeUnpublished;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (request_ == null) {
              Request = new global::OpenSteamworks.Protobuf.WebUI.CStoreBrowse_GetItems_Request();
            }
            input.ReadMessage(Request);
            break;
          }
          case 16: {
            IncludeUnpublished = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (request_ == null) {
              Request = new global::OpenSteamworks.Protobuf.WebUI.CStoreBrowse_GetItems_Request();
            }
            input.ReadMessage(Request);
            break;
          }
          case 16: {
            IncludeUnpublished = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
