// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service_partnerdeadline.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf.WebUI {

  /// <summary>Holder for reflection information generated from service_partnerdeadline.proto</summary>
  public static partial class ServicePartnerdeadlineReflection {

    #region Descriptor
    /// <summary>File descriptor for service_partnerdeadline.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicePartnerdeadlineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1zZXJ2aWNlX3BhcnRuZXJkZWFkbGluZS5wcm90bxogZ29vZ2xlL3Byb3Rv",
            "YnVmL2Rlc2NyaXB0b3IucHJvdG8aEWNvbW1vbl9iYXNlLnByb3RvIqECChBD",
            "UGFydG5lckRlYWRsaW5lEhEKCXBhcnRuZXJpZBgBIAEoDRIWCgR0eXBlGAIg",
            "ASgFQgiCtRgEZW51bRIYCgZzdGF0dXMYAyABKAVCCIK1GARlbnVtEhAKCGR1",
            "ZV9kYXRlGAQgASgNEh0KFWVtYWlsX2RheXNfYmVmb3JlX2R1ZRgFIAMoDRIL",
            "CgNnaWQYBiABKAYSIQoPc3RvcmVfaXRlbV90eXBlGAcgASgFQgiCtRgEZW51",
            "bRIVCg1zdG9yZV9pdGVtX2lkGAggASgNEhkKEWRpc2NvdW50X2V2ZW50X2lk",
            "GAkgASgNEhwKFGRlc2NyaXB0aW9uX2pzb25kYXRhGAogASgJEhcKD3JlcXVp",
            "cmVkX3JpZ2h0cxgLIAEoBCKEAQovQ1BhcnRuZXJEZWFkbGluZV9HZXREZWFk",
            "bGluZXNGb3JQYXJ0bmVyX1JlcXVlc3QSEQoJcGFydG5lcmlkGAEgASgNEhIK",
            "CnN0YXJ0X2RhdGUYAiABKA0SEAoIZW5kX2RhdGUYAyABKA0SGAoQaW5jbHVk",
            "ZV9jb21wbGV0ZRgEIAEoCCJ/CjBDUGFydG5lckRlYWRsaW5lX0dldERlYWRs",
            "aW5lc0ZvclBhcnRuZXJfUmVzcG9uc2USSwoJZGVhZGxpbmVzGAEgAygLMjgu",
            "Q1BhcnRuZXJEZWFkbGluZV9HZXREZWFkbGluZXNGb3JQYXJ0bmVyX1Jlc3Bv",
            "bnNlX1Jlc3VsdCJuCjdDUGFydG5lckRlYWRsaW5lX0dldERlYWRsaW5lc0Zv",
            "clBhcnRuZXJfUmVzcG9uc2VfUmVzdWx0EhIKCmRlYWRsaW5laWQYASABKAYS",
            "HwoEZGF0YRgCIAEoCzIRLkNQYXJ0bmVyRGVhZGxpbmUykAEKD1BhcnRuZXJE",
            "ZWFkbGluZRJ9ChZHZXREZWFkbGluZXNGb3JQYXJ0bmVyEjAuQ1BhcnRuZXJE",
            "ZWFkbGluZV9HZXREZWFkbGluZXNGb3JQYXJ0bmVyX1JlcXVlc3QaMS5DUGFy",
            "dG5lckRlYWRsaW5lX0dldERlYWRsaW5lc0ZvclBhcnRuZXJfUmVzcG9uc2VC",
            "IKoCHU9wZW5TdGVhbXdvcmtzLlByb3RvYnVmLldlYlVJ"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::OpenSteamworks.Protobuf.WebUI.CommonBaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline), global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline.Parser, new[]{ "Partnerid", "Type", "Status", "DueDate", "EmailDaysBeforeDue", "Gid", "StoreItemType", "StoreItemId", "DiscountEventId", "DescriptionJsondata", "RequiredRights" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Request.Parser, new[]{ "Partnerid", "StartDate", "EndDate", "IncludeComplete" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response), global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response.Parser, new[]{ "Deadlines" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result), global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result.Parser, new[]{ "Deadlineid", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDeadline : pb::IMessage<CPartnerDeadline>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDeadline> _parser = new pb::MessageParser<CPartnerDeadline>(() => new CPartnerDeadline());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDeadline> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdeadlineReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline(CPartnerDeadline other) : this() {
      _hasBits0 = other._hasBits0;
      partnerid_ = other.partnerid_;
      type_ = other.type_;
      status_ = other.status_;
      dueDate_ = other.dueDate_;
      emailDaysBeforeDue_ = other.emailDaysBeforeDue_.Clone();
      gid_ = other.gid_;
      storeItemType_ = other.storeItemType_;
      storeItemId_ = other.storeItemId_;
      discountEventId_ = other.discountEventId_;
      descriptionJsondata_ = other.descriptionJsondata_;
      requiredRights_ = other.requiredRights_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline Clone() {
      return new CPartnerDeadline(this);
    }

    /// <summary>Field number for the "partnerid" field.</summary>
    public const int PartneridFieldNumber = 1;
    private readonly static uint PartneridDefaultValue = 0;

    private uint partnerid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Partnerid {
      get { if ((_hasBits0 & 1) != 0) { return partnerid_; } else { return PartneridDefaultValue; } }
      set {
        _hasBits0 |= 1;
        partnerid_ = value;
      }
    }
    /// <summary>Gets whether the "partnerid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPartnerid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "partnerid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPartnerid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private readonly static int TypeDefaultValue = 0;

    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Type {
      get { if ((_hasBits0 & 2) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private readonly static int StatusDefaultValue = 0;

    private int status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Status {
      get { if ((_hasBits0 & 4) != 0) { return status_; } else { return StatusDefaultValue; } }
      set {
        _hasBits0 |= 4;
        status_ = value;
      }
    }
    /// <summary>Gets whether the "status" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStatus {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "status" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStatus() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "due_date" field.</summary>
    public const int DueDateFieldNumber = 4;
    private readonly static uint DueDateDefaultValue = 0;

    private uint dueDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DueDate {
      get { if ((_hasBits0 & 8) != 0) { return dueDate_; } else { return DueDateDefaultValue; } }
      set {
        _hasBits0 |= 8;
        dueDate_ = value;
      }
    }
    /// <summary>Gets whether the "due_date" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDueDate {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "due_date" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDueDate() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "email_days_before_due" field.</summary>
    public const int EmailDaysBeforeDueFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_emailDaysBeforeDue_codec
        = pb::FieldCodec.ForUInt32(40);
    private readonly pbc::RepeatedField<uint> emailDaysBeforeDue_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> EmailDaysBeforeDue {
      get { return emailDaysBeforeDue_; }
    }

    /// <summary>Field number for the "gid" field.</summary>
    public const int GidFieldNumber = 6;
    private readonly static ulong GidDefaultValue = 0UL;

    private ulong gid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Gid {
      get { if ((_hasBits0 & 16) != 0) { return gid_; } else { return GidDefaultValue; } }
      set {
        _hasBits0 |= 16;
        gid_ = value;
      }
    }
    /// <summary>Gets whether the "gid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGid {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "gid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGid() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "store_item_type" field.</summary>
    public const int StoreItemTypeFieldNumber = 7;
    private readonly static int StoreItemTypeDefaultValue = 0;

    private int storeItemType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StoreItemType {
      get { if ((_hasBits0 & 32) != 0) { return storeItemType_; } else { return StoreItemTypeDefaultValue; } }
      set {
        _hasBits0 |= 32;
        storeItemType_ = value;
      }
    }
    /// <summary>Gets whether the "store_item_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStoreItemType {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "store_item_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStoreItemType() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "store_item_id" field.</summary>
    public const int StoreItemIdFieldNumber = 8;
    private readonly static uint StoreItemIdDefaultValue = 0;

    private uint storeItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StoreItemId {
      get { if ((_hasBits0 & 64) != 0) { return storeItemId_; } else { return StoreItemIdDefaultValue; } }
      set {
        _hasBits0 |= 64;
        storeItemId_ = value;
      }
    }
    /// <summary>Gets whether the "store_item_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStoreItemId {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "store_item_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStoreItemId() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "discount_event_id" field.</summary>
    public const int DiscountEventIdFieldNumber = 9;
    private readonly static uint DiscountEventIdDefaultValue = 0;

    private uint discountEventId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DiscountEventId {
      get { if ((_hasBits0 & 128) != 0) { return discountEventId_; } else { return DiscountEventIdDefaultValue; } }
      set {
        _hasBits0 |= 128;
        discountEventId_ = value;
      }
    }
    /// <summary>Gets whether the "discount_event_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDiscountEventId {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "discount_event_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDiscountEventId() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "description_jsondata" field.</summary>
    public const int DescriptionJsondataFieldNumber = 10;
    private readonly static string DescriptionJsondataDefaultValue = "";

    private string descriptionJsondata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DescriptionJsondata {
      get { return descriptionJsondata_ ?? DescriptionJsondataDefaultValue; }
      set {
        descriptionJsondata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "description_jsondata" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDescriptionJsondata {
      get { return descriptionJsondata_ != null; }
    }
    /// <summary>Clears the value of the "description_jsondata" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDescriptionJsondata() {
      descriptionJsondata_ = null;
    }

    /// <summary>Field number for the "required_rights" field.</summary>
    public const int RequiredRightsFieldNumber = 11;
    private readonly static ulong RequiredRightsDefaultValue = 0UL;

    private ulong requiredRights_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequiredRights {
      get { if ((_hasBits0 & 256) != 0) { return requiredRights_; } else { return RequiredRightsDefaultValue; } }
      set {
        _hasBits0 |= 256;
        requiredRights_ = value;
      }
    }
    /// <summary>Gets whether the "required_rights" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRequiredRights {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "required_rights" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequiredRights() {
      _hasBits0 &= ~256;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDeadline);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDeadline other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Partnerid != other.Partnerid) return false;
      if (Type != other.Type) return false;
      if (Status != other.Status) return false;
      if (DueDate != other.DueDate) return false;
      if(!emailDaysBeforeDue_.Equals(other.emailDaysBeforeDue_)) return false;
      if (Gid != other.Gid) return false;
      if (StoreItemType != other.StoreItemType) return false;
      if (StoreItemId != other.StoreItemId) return false;
      if (DiscountEventId != other.DiscountEventId) return false;
      if (DescriptionJsondata != other.DescriptionJsondata) return false;
      if (RequiredRights != other.RequiredRights) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPartnerid) hash ^= Partnerid.GetHashCode();
      if (HasType) hash ^= Type.GetHashCode();
      if (HasStatus) hash ^= Status.GetHashCode();
      if (HasDueDate) hash ^= DueDate.GetHashCode();
      hash ^= emailDaysBeforeDue_.GetHashCode();
      if (HasGid) hash ^= Gid.GetHashCode();
      if (HasStoreItemType) hash ^= StoreItemType.GetHashCode();
      if (HasStoreItemId) hash ^= StoreItemId.GetHashCode();
      if (HasDiscountEventId) hash ^= DiscountEventId.GetHashCode();
      if (HasDescriptionJsondata) hash ^= DescriptionJsondata.GetHashCode();
      if (HasRequiredRights) hash ^= RequiredRights.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      if (HasType) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (HasStatus) {
        output.WriteRawTag(24);
        output.WriteInt32(Status);
      }
      if (HasDueDate) {
        output.WriteRawTag(32);
        output.WriteUInt32(DueDate);
      }
      emailDaysBeforeDue_.WriteTo(output, _repeated_emailDaysBeforeDue_codec);
      if (HasGid) {
        output.WriteRawTag(49);
        output.WriteFixed64(Gid);
      }
      if (HasStoreItemType) {
        output.WriteRawTag(56);
        output.WriteInt32(StoreItemType);
      }
      if (HasStoreItemId) {
        output.WriteRawTag(64);
        output.WriteUInt32(StoreItemId);
      }
      if (HasDiscountEventId) {
        output.WriteRawTag(72);
        output.WriteUInt32(DiscountEventId);
      }
      if (HasDescriptionJsondata) {
        output.WriteRawTag(82);
        output.WriteString(DescriptionJsondata);
      }
      if (HasRequiredRights) {
        output.WriteRawTag(88);
        output.WriteUInt64(RequiredRights);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      if (HasType) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (HasStatus) {
        output.WriteRawTag(24);
        output.WriteInt32(Status);
      }
      if (HasDueDate) {
        output.WriteRawTag(32);
        output.WriteUInt32(DueDate);
      }
      emailDaysBeforeDue_.WriteTo(ref output, _repeated_emailDaysBeforeDue_codec);
      if (HasGid) {
        output.WriteRawTag(49);
        output.WriteFixed64(Gid);
      }
      if (HasStoreItemType) {
        output.WriteRawTag(56);
        output.WriteInt32(StoreItemType);
      }
      if (HasStoreItemId) {
        output.WriteRawTag(64);
        output.WriteUInt32(StoreItemId);
      }
      if (HasDiscountEventId) {
        output.WriteRawTag(72);
        output.WriteUInt32(DiscountEventId);
      }
      if (HasDescriptionJsondata) {
        output.WriteRawTag(82);
        output.WriteString(DescriptionJsondata);
      }
      if (HasRequiredRights) {
        output.WriteRawTag(88);
        output.WriteUInt64(RequiredRights);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPartnerid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Partnerid);
      }
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (HasStatus) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (HasDueDate) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DueDate);
      }
      size += emailDaysBeforeDue_.CalculateSize(_repeated_emailDaysBeforeDue_codec);
      if (HasGid) {
        size += 1 + 8;
      }
      if (HasStoreItemType) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StoreItemType);
      }
      if (HasStoreItemId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StoreItemId);
      }
      if (HasDiscountEventId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DiscountEventId);
      }
      if (HasDescriptionJsondata) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DescriptionJsondata);
      }
      if (HasRequiredRights) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequiredRights);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDeadline other) {
      if (other == null) {
        return;
      }
      if (other.HasPartnerid) {
        Partnerid = other.Partnerid;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasStatus) {
        Status = other.Status;
      }
      if (other.HasDueDate) {
        DueDate = other.DueDate;
      }
      emailDaysBeforeDue_.Add(other.emailDaysBeforeDue_);
      if (other.HasGid) {
        Gid = other.Gid;
      }
      if (other.HasStoreItemType) {
        StoreItemType = other.StoreItemType;
      }
      if (other.HasStoreItemId) {
        StoreItemId = other.StoreItemId;
      }
      if (other.HasDiscountEventId) {
        DiscountEventId = other.DiscountEventId;
      }
      if (other.HasDescriptionJsondata) {
        DescriptionJsondata = other.DescriptionJsondata;
      }
      if (other.HasRequiredRights) {
        RequiredRights = other.RequiredRights;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
          case 24: {
            Status = input.ReadInt32();
            break;
          }
          case 32: {
            DueDate = input.ReadUInt32();
            break;
          }
          case 42:
          case 40: {
            emailDaysBeforeDue_.AddEntriesFrom(input, _repeated_emailDaysBeforeDue_codec);
            break;
          }
          case 49: {
            Gid = input.ReadFixed64();
            break;
          }
          case 56: {
            StoreItemType = input.ReadInt32();
            break;
          }
          case 64: {
            StoreItemId = input.ReadUInt32();
            break;
          }
          case 72: {
            DiscountEventId = input.ReadUInt32();
            break;
          }
          case 82: {
            DescriptionJsondata = input.ReadString();
            break;
          }
          case 88: {
            RequiredRights = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
          case 24: {
            Status = input.ReadInt32();
            break;
          }
          case 32: {
            DueDate = input.ReadUInt32();
            break;
          }
          case 42:
          case 40: {
            emailDaysBeforeDue_.AddEntriesFrom(ref input, _repeated_emailDaysBeforeDue_codec);
            break;
          }
          case 49: {
            Gid = input.ReadFixed64();
            break;
          }
          case 56: {
            StoreItemType = input.ReadInt32();
            break;
          }
          case 64: {
            StoreItemId = input.ReadUInt32();
            break;
          }
          case 72: {
            DiscountEventId = input.ReadUInt32();
            break;
          }
          case 82: {
            DescriptionJsondata = input.ReadString();
            break;
          }
          case 88: {
            RequiredRights = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDeadline_GetDeadlinesForPartner_Request : pb::IMessage<CPartnerDeadline_GetDeadlinesForPartner_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Request> _parser = new pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Request>(() => new CPartnerDeadline_GetDeadlinesForPartner_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdeadlineReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Request(CPartnerDeadline_GetDeadlinesForPartner_Request other) : this() {
      _hasBits0 = other._hasBits0;
      partnerid_ = other.partnerid_;
      startDate_ = other.startDate_;
      endDate_ = other.endDate_;
      includeComplete_ = other.includeComplete_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Request Clone() {
      return new CPartnerDeadline_GetDeadlinesForPartner_Request(this);
    }

    /// <summary>Field number for the "partnerid" field.</summary>
    public const int PartneridFieldNumber = 1;
    private readonly static uint PartneridDefaultValue = 0;

    private uint partnerid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Partnerid {
      get { if ((_hasBits0 & 1) != 0) { return partnerid_; } else { return PartneridDefaultValue; } }
      set {
        _hasBits0 |= 1;
        partnerid_ = value;
      }
    }
    /// <summary>Gets whether the "partnerid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPartnerid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "partnerid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPartnerid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "start_date" field.</summary>
    public const int StartDateFieldNumber = 2;
    private readonly static uint StartDateDefaultValue = 0;

    private uint startDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StartDate {
      get { if ((_hasBits0 & 2) != 0) { return startDate_; } else { return StartDateDefaultValue; } }
      set {
        _hasBits0 |= 2;
        startDate_ = value;
      }
    }
    /// <summary>Gets whether the "start_date" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStartDate {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "start_date" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStartDate() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "end_date" field.</summary>
    public const int EndDateFieldNumber = 3;
    private readonly static uint EndDateDefaultValue = 0;

    private uint endDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EndDate {
      get { if ((_hasBits0 & 4) != 0) { return endDate_; } else { return EndDateDefaultValue; } }
      set {
        _hasBits0 |= 4;
        endDate_ = value;
      }
    }
    /// <summary>Gets whether the "end_date" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEndDate {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "end_date" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEndDate() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "include_complete" field.</summary>
    public const int IncludeCompleteFieldNumber = 4;
    private readonly static bool IncludeCompleteDefaultValue = false;

    private bool includeComplete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeComplete {
      get { if ((_hasBits0 & 8) != 0) { return includeComplete_; } else { return IncludeCompleteDefaultValue; } }
      set {
        _hasBits0 |= 8;
        includeComplete_ = value;
      }
    }
    /// <summary>Gets whether the "include_complete" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIncludeComplete {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "include_complete" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIncludeComplete() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDeadline_GetDeadlinesForPartner_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDeadline_GetDeadlinesForPartner_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Partnerid != other.Partnerid) return false;
      if (StartDate != other.StartDate) return false;
      if (EndDate != other.EndDate) return false;
      if (IncludeComplete != other.IncludeComplete) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPartnerid) hash ^= Partnerid.GetHashCode();
      if (HasStartDate) hash ^= StartDate.GetHashCode();
      if (HasEndDate) hash ^= EndDate.GetHashCode();
      if (HasIncludeComplete) hash ^= IncludeComplete.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      if (HasStartDate) {
        output.WriteRawTag(16);
        output.WriteUInt32(StartDate);
      }
      if (HasEndDate) {
        output.WriteRawTag(24);
        output.WriteUInt32(EndDate);
      }
      if (HasIncludeComplete) {
        output.WriteRawTag(32);
        output.WriteBool(IncludeComplete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      if (HasStartDate) {
        output.WriteRawTag(16);
        output.WriteUInt32(StartDate);
      }
      if (HasEndDate) {
        output.WriteRawTag(24);
        output.WriteUInt32(EndDate);
      }
      if (HasIncludeComplete) {
        output.WriteRawTag(32);
        output.WriteBool(IncludeComplete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPartnerid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Partnerid);
      }
      if (HasStartDate) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StartDate);
      }
      if (HasEndDate) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EndDate);
      }
      if (HasIncludeComplete) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDeadline_GetDeadlinesForPartner_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasPartnerid) {
        Partnerid = other.Partnerid;
      }
      if (other.HasStartDate) {
        StartDate = other.StartDate;
      }
      if (other.HasEndDate) {
        EndDate = other.EndDate;
      }
      if (other.HasIncludeComplete) {
        IncludeComplete = other.IncludeComplete;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 16: {
            StartDate = input.ReadUInt32();
            break;
          }
          case 24: {
            EndDate = input.ReadUInt32();
            break;
          }
          case 32: {
            IncludeComplete = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 16: {
            StartDate = input.ReadUInt32();
            break;
          }
          case 24: {
            EndDate = input.ReadUInt32();
            break;
          }
          case 32: {
            IncludeComplete = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDeadline_GetDeadlinesForPartner_Response : pb::IMessage<CPartnerDeadline_GetDeadlinesForPartner_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Response> _parser = new pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Response>(() => new CPartnerDeadline_GetDeadlinesForPartner_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdeadlineReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Response(CPartnerDeadline_GetDeadlinesForPartner_Response other) : this() {
      deadlines_ = other.deadlines_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Response Clone() {
      return new CPartnerDeadline_GetDeadlinesForPartner_Response(this);
    }

    /// <summary>Field number for the "deadlines" field.</summary>
    public const int DeadlinesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result> _repeated_deadlines_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result> deadlines_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline_GetDeadlinesForPartner_Response_Result> Deadlines {
      get { return deadlines_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDeadline_GetDeadlinesForPartner_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDeadline_GetDeadlinesForPartner_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!deadlines_.Equals(other.deadlines_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= deadlines_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      deadlines_.WriteTo(output, _repeated_deadlines_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      deadlines_.WriteTo(ref output, _repeated_deadlines_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += deadlines_.CalculateSize(_repeated_deadlines_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDeadline_GetDeadlinesForPartner_Response other) {
      if (other == null) {
        return;
      }
      deadlines_.Add(other.deadlines_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            deadlines_.AddEntriesFrom(input, _repeated_deadlines_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            deadlines_.AddEntriesFrom(ref input, _repeated_deadlines_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerDeadline_GetDeadlinesForPartner_Response_Result : pb::IMessage<CPartnerDeadline_GetDeadlinesForPartner_Response_Result>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Response_Result> _parser = new pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Response_Result>(() => new CPartnerDeadline_GetDeadlinesForPartner_Response_Result());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerDeadline_GetDeadlinesForPartner_Response_Result> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnerdeadlineReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Response_Result() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Response_Result(CPartnerDeadline_GetDeadlinesForPartner_Response_Result other) : this() {
      _hasBits0 = other._hasBits0;
      deadlineid_ = other.deadlineid_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerDeadline_GetDeadlinesForPartner_Response_Result Clone() {
      return new CPartnerDeadline_GetDeadlinesForPartner_Response_Result(this);
    }

    /// <summary>Field number for the "deadlineid" field.</summary>
    public const int DeadlineidFieldNumber = 1;
    private readonly static ulong DeadlineidDefaultValue = 0UL;

    private ulong deadlineid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Deadlineid {
      get { if ((_hasBits0 & 1) != 0) { return deadlineid_; } else { return DeadlineidDefaultValue; } }
      set {
        _hasBits0 |= 1;
        deadlineid_ = value;
      }
    }
    /// <summary>Gets whether the "deadlineid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDeadlineid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "deadlineid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDeadlineid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerDeadline_GetDeadlinesForPartner_Response_Result);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerDeadline_GetDeadlinesForPartner_Response_Result other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Deadlineid != other.Deadlineid) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDeadlineid) hash ^= Deadlineid.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDeadlineid) {
        output.WriteRawTag(9);
        output.WriteFixed64(Deadlineid);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDeadlineid) {
        output.WriteRawTag(9);
        output.WriteFixed64(Deadlineid);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasDeadlineid) {
        size += 1 + 8;
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerDeadline_GetDeadlinesForPartner_Response_Result other) {
      if (other == null) {
        return;
      }
      if (other.HasDeadlineid) {
        Deadlineid = other.Deadlineid;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Deadlineid = input.ReadFixed64();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Deadlineid = input.ReadFixed64();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::OpenSteamworks.Protobuf.WebUI.CPartnerDeadline();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
