// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: steammessages_unified_base.steamclient.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf {

  /// <summary>Holder for reflection information generated from steammessages_unified_base.steamclient.proto</summary>
  public static partial class SteammessagesUnifiedBaseSteamclientReflection {

    #region Descriptor
    /// <summary>File descriptor for steammessages_unified_base.steamclient.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SteammessagesUnifiedBaseSteamclientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixzdGVhbW1lc3NhZ2VzX3VuaWZpZWRfYmFzZS5zdGVhbWNsaWVudC5wcm90",
            "bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG8iDAoKTm9SZXNw",
            "b25zZSpZChNFUHJvdG9FeGVjdXRpb25TaXRlEh4KGkVQcm90b0V4ZWN1dGlv",
            "blNpdGVVbmtub3duEAASIgoeRVByb3RvRXhlY3V0aW9uU2l0ZVN0ZWFtQ2xp",
            "ZW50EAIqYQoRRVByb3RvU2VydmljZVR5cGUSIgoeRVByb3RvU2VydmljZVR5",
            "cGVTdGVhbU1lc3NhZ2VzEAASKAokRVByb3RvU2VydmljZVR5cGVWUkdhbWVw",
            "YWRVSU1lc3NhZ2VzEAE6PgoTbWVzc2FnZV9kZXNjcmlwdGlvbhIfLmdvb2ds",
            "ZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxi4jgMgASgJOkQKEmZvcmNlX2Vt",
            "aXRfbWVzc2FnZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjq",
            "hgMgASgIOgVmYWxzZTo0CgtkZXNjcmlwdGlvbhIdLmdvb2dsZS5wcm90b2J1",
            "Zi5GaWVsZE9wdGlvbnMY0IYDIAEoCTo+ChNzZXJ2aWNlX2Rlc2NyaXB0aW9u",
            "Eh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGNCGAyABKAk6cwoW",
            "c2VydmljZV9leGVjdXRpb25fc2l0ZRIfLmdvb2dsZS5wcm90b2J1Zi5TZXJ2",
            "aWNlT3B0aW9ucxjYhgMgASgOMhQuRVByb3RvRXhlY3V0aW9uU2l0ZToaRVBy",
            "b3RvRXhlY3V0aW9uU2l0ZVVua25vd246awoMc2VydmljZV90eXBlEh8uZ29v",
            "Z2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGOmGAyABKA4yEi5FUHJvdG9T",
            "ZXJ2aWNlVHlwZToeRVByb3RvU2VydmljZVR5cGVTdGVhbU1lc3NhZ2VzOkQK",
            "EmZvcmNlX2VtaXRfc2VydmljZRIfLmdvb2dsZS5wcm90b2J1Zi5TZXJ2aWNl",
            "T3B0aW9ucxjqhgMgASgIOgVmYWxzZTo8ChJtZXRob2RfZGVzY3JpcHRpb24S",
            "Hi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxjQhgMgASgJOjgKEGVu",
            "dW1fZGVzY3JpcHRpb24SHC5nb29nbGUucHJvdG9idWYuRW51bU9wdGlvbnMY",
            "0IYDIAEoCTpDChZlbnVtX3ZhbHVlX2Rlc2NyaXB0aW9uEiEuZ29vZ2xlLnBy",
            "b3RvYnVmLkVudW1WYWx1ZU9wdGlvbnMY0IYDIAEoCUIfSAGAAQCqAhdPcGVu",
            "U3RlYW13b3Jrcy5Qcm90b2J1Zg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OpenSteamworks.Protobuf.EProtoExecutionSite), typeof(global::OpenSteamworks.Protobuf.EProtoServiceType), }, new pb::Extension[] { SteammessagesUnifiedBaseSteamclientExtensions.MessageDescription, SteammessagesUnifiedBaseSteamclientExtensions.ForceEmitMessage, SteammessagesUnifiedBaseSteamclientExtensions.Description, SteammessagesUnifiedBaseSteamclientExtensions.ServiceDescription, SteammessagesUnifiedBaseSteamclientExtensions.ServiceExecutionSite, SteammessagesUnifiedBaseSteamclientExtensions.ServiceType, SteammessagesUnifiedBaseSteamclientExtensions.ForceEmitService, SteammessagesUnifiedBaseSteamclientExtensions.MethodDescription, SteammessagesUnifiedBaseSteamclientExtensions.EnumDescription, SteammessagesUnifiedBaseSteamclientExtensions.EnumValueDescription }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.NoResponse), global::OpenSteamworks.Protobuf.NoResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of steammessages_unified_base.steamclient.proto</summary>
  public static partial class SteammessagesUnifiedBaseSteamclientExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> MessageDescription =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(51000, pb::FieldCodec.ForString(408002, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> ForceEmitMessage =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(50026, pb::FieldCodec.ForBool(400208, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Description =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, string> ServiceDescription =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::OpenSteamworks.Protobuf.EProtoExecutionSite> ServiceExecutionSite =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::OpenSteamworks.Protobuf.EProtoExecutionSite>(50008, pb::FieldCodec.ForEnum(400064, x => (int) x, x => (global::OpenSteamworks.Protobuf.EProtoExecutionSite) x, global::OpenSteamworks.Protobuf.EProtoExecutionSite.Unknown));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::OpenSteamworks.Protobuf.EProtoServiceType> ServiceType =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::OpenSteamworks.Protobuf.EProtoServiceType>(50025, pb::FieldCodec.ForEnum(400200, x => (int) x, x => (global::OpenSteamworks.Protobuf.EProtoServiceType) x, global::OpenSteamworks.Protobuf.EProtoServiceType.SteamMessages));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, bool> ForceEmitService =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, bool>(50026, pb::FieldCodec.ForBool(400208, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, string> MethodDescription =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumOptions, string> EnumDescription =
      new pb::Extension<global::Google.Protobuf.Reflection.EnumOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> EnumValueDescription =
      new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  }

  #region Enums
  public enum EProtoExecutionSite {
    [pbr::OriginalName("EProtoExecutionSiteUnknown")] Unknown = 0,
    [pbr::OriginalName("EProtoExecutionSiteSteamClient")] SteamClient = 2,
  }

  public enum EProtoServiceType {
    [pbr::OriginalName("EProtoServiceTypeSteamMessages")] SteamMessages = 0,
    [pbr::OriginalName("EProtoServiceTypeVRGamepadUIMessages")] VrgamepadUimessages = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NoResponse : pb::IMessage<NoResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NoResponse> _parser = new pb::MessageParser<NoResponse>(() => new NoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.SteammessagesUnifiedBaseSteamclientReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NoResponse(NoResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NoResponse Clone() {
      return new NoResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NoResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
